### ISSUE TITLE
Camera is always called "OBS-Camera"

### ISSUE THREAD

**Issue by link00000000** [link00000000/mimic#3]
Might be able to be solved by modifying a DLL after installation.

See CatxFish/obs-virtual-cam#90

**Comment by markoPopchkin** [comment]
Hey! Were you able to solve this problem? I really need help.
I can't change the name in any way

**Comment by Mason-Roberts** [comment]
> 
> 
> Hey! Were you able to solve this problem? I really need help.
> I can't change the name in any way

The name is from a Windows registry. You would have to change its value to change the name displayed with the virtual camera.

In the registry editor:

- Path: "Computer\HKEY_CLASSES_ROOT\CLSID\{860BB310-5D01-11d0-BD3B-00A0C911CE86}\Instance\{27B05C2D-93DC-474A-A5DA-9BBA34CB2A9C}"
- The value to change is under the "Friendly Name"

If you have any more questions, just let me know.

Code example from the repository:
Lines 68-75
https://github.com/link00000000/mimic/blob/master/setup.iss

**Comment by BJSam** [comment]
my path pattern was bit different 
Path: `Computer\HKEY_CLASSES_ROOT\CLSID\{860BB310-5D01-11d0-BD3B-00A0C911CE86}\Instance` then it is `\{A3FCE0F5-3493-419F-958A-ABA1250EC20B}`

and default name was "OBS Virtual Camera"

**Comment by UnknwonWarlock** [comment]
> 
> 
> my path pattern was bit different
> Path: `Computer\HKEY_CLASSES_ROOT\CLSID\{860BB310-5D01-11d0-BD3B-00A0C911CE86}\Instance` then it is `\{A3FCE0F5-3493-419F-958A-ABA1250EC20B}`
> 
> and default name was "OBS Virtual Camera"

This might lead to an issue with changing the name of the camera during Mimic's setup. If you can give details on how you started using OBS Virtual Camera. Are you using it with Mimic or did you already have it installed?

**Comment by BJSam** [comment]
> 
> 
> > my path pattern was bit different
> > Path: `Computer\HKEY_CLASSES_ROOT\CLSID\{860BB310-5D01-11d0-BD3B-00A0C911CE86}\Instance` then it is `\{A3FCE0F5-3493-419F-958A-ABA1250EC20B}`
> > and default name was "OBS Virtual Camera"
> 
> This might lead to an issue with changing the name of the camera during Mimic's setup. If you can give details on how you started using OBS Virtual Camera. Are you using it with Mimic or did you already have it installed?

sry I forgot to mention 

I am using latest version of OBS, it comes with virtual camera.
and changes what i did its working fine. I got no issues.

BTW if we can change camera pixels size it will be great. Now for me in web I see my virtual cam is of 2MP. Is there any way to change it.
